### ISSUE TITLE
F# precompiled + FAKE + Paket

### ISSUE THREAD

**Issue by Angr1st** [mikhailshilkov/azure-functions-fsharp-examples#2]
Hello @mikhailshilkov  I really like your examples but I'm wondering If you've ever tried using the combination of precompiled FSharp Azure Functions + FAKE + Package?

**Comment by mikhailshilkov** [comment]
I had one with Paket (see example 8) but I haven't used FAKE

**Comment by Angr1st** [comment]
I got it working. If you are interested I uploaded it to github [here](https://github.com/Angr1st/AzureFunctionFAKEPaket).
